/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as BillsIndexImport } from './routes/bills/index'
import { Route as BillsBillIdImport } from './routes/bills/$billId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const BillsIndexRoute = BillsIndexImport.update({
  id: '/bills/',
  path: '/bills/',
  getParentRoute: () => rootRoute,
} as any)

const BillsBillIdRoute = BillsBillIdImport.update({
  id: '/bills/$billId',
  path: '/bills/$billId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/bills/$billId': {
      id: '/bills/$billId'
      path: '/bills/$billId'
      fullPath: '/bills/$billId'
      preLoaderRoute: typeof BillsBillIdImport
      parentRoute: typeof rootRoute
    }
    '/bills/': {
      id: '/bills/'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof BillsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bills/$billId': typeof BillsBillIdRoute
  '/bills': typeof BillsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bills/$billId': typeof BillsBillIdRoute
  '/bills': typeof BillsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/bills/$billId': typeof BillsBillIdRoute
  '/bills/': typeof BillsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bills/$billId' | '/bills'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bills/$billId' | '/bills'
  id: '__root__' | '/' | '/bills/$billId' | '/bills/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BillsBillIdRoute: typeof BillsBillIdRoute
  BillsIndexRoute: typeof BillsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BillsBillIdRoute: BillsBillIdRoute,
  BillsIndexRoute: BillsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/bills/$billId",
        "/bills/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/bills/$billId": {
      "filePath": "bills/$billId.tsx"
    },
    "/bills/": {
      "filePath": "bills/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
